# Introduction to TensorFlow

**TensorFlow** is an open-source machine learning library developed by Google, designed for building and training deep learning models. It uses **computational graphs** to represent data flow and supports efficient execution across **diverse hardware platforms**, including **CPUs, GPUs, and TPUs**. TensorFlow offers two execution modes: **eager execution** for intuitive, step-by-step debugging, and **graph execution** for optimized performance in production environments. At its core, TensorFlow relies on **tensors** (multi-dimensional arrays) that store and manipulate data throughout the model lifecycle, from input preprocessing to output prediction.

## Configuration

This section sets up the environment by installing and importing TensorFlow, preparing it for use throughout the notebook.

In [ ]:
# If you're running this notebook in Google Colab, TensorFlow is usually pre-installed.
# To be sure, you can uncomment the line below and run it to install TensorFlow manually.

# !pip install tensorflow

In [2]:
# Import TensorFlow
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


## Tensors

Tensors are the fundamental data structure in TensorFlow and they represent the flow of data through a computation graph. Tensors generalize scalars, vectors and matrices to higher dimensions. A tensor, in TensorFlow, is an object defined by:
- **Shape:** Its dimensions (e.g., [2, 3] for a 2×3 matrix)
- **Rank:** Number of dimensions (e.g., scalar = 0, vector = 1, matrix = 2)
- **Data type:** Element type like float32, int32, or string
- **Device:** Hardware location such as CPU or GPU

In [17]:
# Create a 2x3 tensor with float32 data type
tensor = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=tf.float32)

# Display tensor properties
print("Tensor:", tensor)                 # tf.Tensor([[1. 2. 3.] [4. 5. 6.]], shape=(2, 3), dtype=float32)
print("Shape:", tensor.shape)            # [2, 3]
print("Rank:", tf.rank(tensor).numpy())  # 2
print("Data type:", tensor.dtype)        # float32
print("Device:", tensor.device)          # e.g., '/job:localhost/replica:0/task:0/device:CPU:0'


Tensor: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
Shape: (2, 3)
Rank: 2
Data type: <dtype: 'float32'>
Device: /job:localhost/replica:0/task:0/device:CPU:0


### Basic TensorFlow operations

TensorFlow provides a plethora of mathematical operations for manipulating tensors. The numerical operations include addition, subtraction, multiplication, division, and more:
- `tf.constant()` is used for defining tensors.
- `tf.add` is used to perform element-wise addition on tensors a and b.
- `tf.subtract` is used for element-wise subtraction.
- `tf.multiply` performs element-wise multiplication.
- `tf.divide` is used for element-wise division.

In [22]:
import tensorflow as tf

# Define two tensors
a = tf.constant([2, 4, 6])
b = tf.constant([1, 2, 3])

# Perform element-wise operations
add_result = tf.add(a, b)
sub_result = tf.subtract(a, b)
mul_result = tf.multiply(a, b)
div_result = tf.divide(a, b)

# Display results
print("Tensor a:", a)
print("Tensor b:", b)
print("Addition (a + b):", add_result)
print("Subtraction (a - b):", sub_result)
print("Multiplication (a * b):", mul_result)
print("Division (a / b):", div_result)


Tensor a: tf.Tensor([2 4 6], shape=(3,), dtype=int32)
Tensor b: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Addition (a + b): tf.Tensor([3 6 9], shape=(3,), dtype=int32)
Subtraction (a - b): tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Multiplication (a * b): tf.Tensor([ 2  8 18], shape=(3,), dtype=int32)
Division (a / b): tf.Tensor([2. 2. 2.], shape=(3,), dtype=float64)


In [ ]:
# Try to use normal operatrions (+, -, *, /) with tensors instead of tf functions !

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 6]], dtype=int32)>

### Basic tensor transformations

TensorFlow proposes many tensor transformations that modify tensors without changing their underlying data. These transformations include reshaping, transposing, casting, and slicing, and are key to preparing data for model training and evaluation in TensorFlow.

In [ ]:
# Base tensor
x = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32)

# 1. tf.reshape
reshaped = tf.reshape(x, [2, 3])
print("Reshaped (2x3):\n", reshaped.numpy())

# 2. tf.expand_dims
expanded = tf.expand_dims(x, axis=0)
print("\nExpanded dims (axis=0):\n", expanded.numpy())

# 3. tf.squeeze
squeezed = tf.squeeze(expanded)
print("\nSqueezed:\n", squeezed.numpy())

# 4. tf.transpose
transposed = tf.transpose(x)
print("\nTransposed:\n", transposed.numpy())

# 5. tf.reverse
reversed_tensor = tf.reverse(x, axis=[0])
print("\nReversed (axis=0):\n", reversed_tensor.numpy()

# 6. tf.roll
rolled = tf.roll(x, shift=1, axis=0)
print("\nRolled (shift=1, axis=0):\n", rolled.numpy())

# 7. tf.concat
a = tf.constant([[1, 2]])
b = tf.constant([[3, 4]])
concatenated = tf.concat([a, b], axis=0)
print("\nConcatenated:\n", concatenated.numpy())

# 8. tf.stack
stacked = tf.stack([a, b], axis=0)
print("\nStacked:\n", stacked.numpy())

# 9. tf.unstack
unstacked = tf.unstack(x, axis=0)
print("\nUnstacked:")
for i, t in enumerate(unstacked):
    print(f"Slice {i}:\n", t.numpy())

# 10. tf.split
split = tf.split(x, num_or_size_splits=3, axis=0)
print("\nSplit:")
for i, t in enumerate(split):
    print(f"Part {i}:\n", t.numpy())

# 11. tf.cast
casted = tf.cast(x, tf.int32)
print("\nCasted to int32:\n", casted.numpy())

# 12. tf.clip_by_value
clipped = tf.clip_by_value(x, clip_value_min=2.0, clip_value_max=5.0)
print("\nClipped (min=2, max=5):\n", clipped.numpy())

# 13. tf.where
condition = tf.constant([[True, False], [False, True], [True, True]])
selected = tf.where(condition, x, tf.zeros_like(x))
print("\nWhere condition:\n", selected.numpy())

# 14. tf.pad
padded = tf.pad(x, paddings=[[1, 1], [1, 1]])
print("\nPadded:\n", padded.numpy())

# 15. tf.slice
sliced = tf.slice(x, begin=[0, 0], size=[2, 2])
print("\nSliced (first 2 rows, 2 cols):\n", sliced.numpy())

# Reorder using tf.sort (ascending)
sorted_tensor = tf.sort(x, direction='ASCENDING')
print("Sorted tensor (ascending):", sorted_tensor.numpy())

# Shuffle along the first dimension (rows)
shuffled = tf.random.shuffle(x)

print("Original tensor:\n", x.numpy())
print("\nShuffled tensor (rows randomly reordered):\n", shuffled.numpy())

Reshaped (2x3):
 [[1. 2. 3.]
 [4. 5. 6.]]

Expanded dims (axis=0):
 [[[1. 2.]
  [3. 4.]
  [5. 6.]]]

Squeezed:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

Transposed:
 [[1. 3. 5.]
 [2. 4. 6.]]

Reversed (axis=0):
 [[5. 6.]
 [3. 4.]
 [1. 2.]]

Rolled (shift=1, axis=0):
 [[5. 6.]
 [1. 2.]
 [3. 4.]]

Concatenated:
 [[1 2]
 [3 4]]

Stacked:
 [[[1 2]]

 [[3 4]]]

Unstacked:
Slice 0:
 [1. 2.]
Slice 1:
 [3. 4.]
Slice 2:
 [5. 6.]

Split:
Part 0:
 [[1. 2.]]
Part 1:
 [[3. 4.]]
Part 2:
 [[5. 6.]]

Casted to int32:
 [[1 2]
 [3 4]
 [5 6]]

Clipped (min=2, max=5):
 [[2. 2.]
 [3. 4.]
 [5. 5.]]

Where condition:
 [[1. 0.]
 [0. 4.]
 [5. 6.]]

Padded:
 [[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 5. 6. 0.]
 [0. 0. 0. 0.]]

Sliced (first 2 rows, 2 cols):
 [[1. 2.]
 [3. 4.]]
Sorted tensor (ascending): [[1. 2.]
 [3. 4.]
 [5. 6.]]
Original tensor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

Shuffled tensor (rows randomly reordered):
 [[3. 4.]
 [5. 6.]
 [1. 2.]]


### NumPy compatibility

Converting between a TensorFlow `tf.Tensor` and a NumPy `ndarray` is easy:

* TensorFlow operations automatically convert NumPy ndarrays to Tensors.
* NumPy operations automatically convert Tensors to NumPy ndarrays.

Tensors are explicitly converted to NumPy ndarrays using their `.numpy()` method. These conversions are typically cheap since the array and `tf.Tensor` share the underlying memory representation, if possible. However, sharing the underlying representation isn't always possible since the `tf.Tensor` may be hosted in GPU memory while NumPy arrays are always backed by host memory, and the conversion involves a copy from GPU to host memory.

In [13]:
import numpy as np

ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.math.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to NumPy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to NumPy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


### Execution Modes in TensorFlow

TensorFlow 2 simplifies development by blending two execution modes:

- **Eager Execution:** Runs operations immediately, making it intuitive and Pythonic. Ideal for beginners, debugging, and rapid prototyping.
- **Graph-Based Execution:** Builds a computational graph for optimized performance. Best suited for large-scale models and production deployment.

With TensorFlow 2’s mixed approach, you can start in eager mode and later convert functions to graph mode using @tf.function. This lets you retain ease of use while gaining speed and scalability.

In [1]:
import timeit
import tensorflow as tf
# Eager function
def func_eager(a,b):
    return a*b
# Graph function using tf.function on eager func
@tf.function
def graph_func(a,b): 
    return a*b 

a = tf.constant([2]) 
b = tf.constant([5])
# Eager execution
print("Eager execution:",timeit.timeit(lambda:func_eager(a,b),number=100)) # Function with graph execution
print("Graph execution:",timeit.timeit(lambda: graph_func(a,b),number=100)) 
print("For simple operations Graph execution takes more time..")

Eager execution: 0.016597699839621782
Graph execution: 0.18765489989891648
For simple operations Graph execution takes more time..


In [5]:
# TensorFlow imports
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Flatten, Dense
# Define the model (Inspired by mnist inputs) 
model = tf.keras.Sequential() 
model.add(tf.keras.Input(shape=(28,28,))) 
model.add(Flatten()) 
model.add(Dense(256,"relu")) 
model.add(Dense(128,"relu")) 
model.add(Dense(256,"relu"))
model.add(Dense(10,"softmax")) 


# Dummy data with MNIST image sizes 
X = tf.random.uniform([1000, 28, 28])
# Eager Execution to do inference (Model untrained as we are evaluating speed of inference)
eager_model = model
print("Eager time:", timeit.timeit(lambda: eager_model(X,training=False), number=100))
#Graph Execution to do inference (Model untrained as we are evaluating speed of inference)
graph_model = tf.function(eager_model) 
# Wrap the model with tf.function 
print("Graph time:", timeit.timeit(lambda: graph_model(X,training=False), number=100))

Eager time: 2.08488139975816
Graph time: 0.9481501001864672


### Device Execution in TensorFlow: CPU, GPU, and TPU

TensorFlow is designed to run computations efficiently across different hardware devices:

- **CPU (Central Processing Unit):** Default execution device. Suitable for general-purpose tasks and small-scale models.
- **GPU (Graphics Processing Unit):** Accelerates parallel computations, ideal for training deep learning models.
- **TPU (Tensor Processing Unit):** Specialized hardware developed by Google for large-scale machine learning workloads.

TensorFlow automatically assigns operations to available devices, but you can also manually place operations on a specific device using tf.device().

⚠️ Note: GPU and TPU support depends on your environment. Google Colab typically provides GPU/TPU options via Runtime > Change runtime type.

In [11]:
import tensorflow as tf
import time

# Create large tensors for demonstration
x = tf.random.uniform([10000, 1000])
y = tf.random.uniform([1000, 1000])

# CPU execution
with tf.device('/CPU:0'):
    start_cpu = time.time()
    result_cpu = tf.linalg.matmul(x, y)
    end_cpu = time.time()
    print("CPU execution time: {:.4f} seconds".format(end_cpu - start_cpu))

# GPU execution (if available)
if tf.config.list_physical_devices('GPU'):
    with tf.device('/GPU:0'):
        start_gpu = time.time()
        result_gpu = tf.linalg.matmul(x, y)
        end_gpu = time.time()
        print("GPU execution time: {:.4f} seconds".format(end_gpu - start_gpu))
else:
    print("No GPU found. Skipping GPU test.")

CPU execution time: 0.3260 seconds
No GPU found. Skipping GPU test.


In [7]:
# List all physical devices recognized by TensorFlow
print("Available devices:")
for device in tf.config.list_physical_devices():
    print(device)

Available devices:
PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')


## Datasets

This section uses the `tf.data.Dataset` API to build a pipeline for feeding data to your model.

### Create a source `Dataset`

Create a *source* dataset using one of the factory functions like `tf.data.Dataset.from_tensors`, `tf.data.Dataset.from_tensor_slices`, or using objects that read from files like `tf.data.TextLineDataset` or `tf.data.TFRecordDataset`. Refer to the _Reading input data_ section of the [tf.data: Build TensorFlow input pipelines](../../guide/data.ipynb) guide for more information.

In [7]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

### Apply transformations

Use the transformations functions like `tf.data.Dataset.map`, `tf.data.Dataset.batch`, and `tf.data.Dataset.shuffle` to apply transformations to dataset records.

In [11]:
ds_tensors = ds_tensors.map(tf.math.square).shuffle(2).batch(2)

### Iterate

`tf.data.Dataset` objects support iteration to loop over records:

In [12]:
print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)

Elements of ds_tensors:
tf.Tensor([4 9], shape=(2,), dtype=int32)
tf.Tensor([ 1 25], shape=(2,), dtype=int32)
tf.Tensor([16 36], shape=(2,), dtype=int32)
